
version: '2.1'

services:

	gitlab:
      image: gitlab/gitlab-ce
      container_name: gitlab
      restart: unless-stopped
      privileged: true
      hostname: gitlab
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://127.0.0.1'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = 'smtp.aliyun.com'
          gitlab_rails['smtp_port'] = 465
          gitlab_rails['smtp_user_name'] = 'zy251021@aliyun.com'
          gitlab_rails['smtp_password'] = 'g3nt00567'
          gitlab_rails['smtp_domain'] = 'aliyun.com'
          gitlab_rails['smtp_authentication'] = 'login'
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = true
          gitlab_rails['gitlab_email_from'] = 'zy251021@aliyun.com'
          gitlab_rails['gitlab_shell_ssh_port'] = 22
      ports:
        - '8085:22'
        - '8084:80'
        - '8083:443'
      volumes:
        - ../data/gitlab/etc:/etc/gitlab
        - ../data/gitlab/opt:/var/opt/gitlab
        - ../data/gitlab/log:/var/log/gitlab
