version: '2.1'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --disable-log-bin --innodb-flush-log-at-trx-commit=2
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ../../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: g3nt00567

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80 
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis
    container_name: redis
    command: ["redis-server"]
    restart: always
    ports:
      - 6379:6379
    sysctls:
      - net.core.somaxconn=1024
    volumes:
      - ../../data/redis:/data

  phpredmin:
    image: sasanrose/phpredmin
    container_name: phpredmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../../data/mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: g3nt00567

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: g3nt00567
